# https://crontab.io/

name: Daily Greeting
on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  greet1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Good morning, team!"

  greet2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Good afternoon, team!"

  greet3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Good evening, team!"

  greet4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Good night, team!"    
greet5:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Good night, team!"    
